### PR TITLE
json parsing improvements & fixes

### PR DESCRIPTION
**Pull request by rvagg**
~~This isn't a fix, it's just a placeholder (demonstration) of some cases that should fail that don't and some that fail with errors messages that are inappropriate. Posting this here while I notice it, perhaps I'll come back and fix soon!~~

More tests added; fixes applied; more comprehensive testing done via https://github.com/ipld/go-ipld-prime/pull/550

### CODE REVIEW

**Comment by rvagg** [comment]
added a fix, but it's non-trivial as we have to manage a bit more state than just "what's next?" in a stack - the "have we done the first one?" needs to be preserved across stack frames

will do some testing with more round-trips using ipld-garbage to see if this breaks anywhere interesting where it shouldn't

**Comment by warpfork** [comment]
(lgtm)

**Review by willscott — APPROVED** [review]

**Comment by rvagg** [comment]
https://github.com/ipld/go-ipld-prime/pull/550 looks good, I feel more confident about these changes now

**Comment by warpfork** [comment]
Per @rvagg 's nudge in another channel that you're happy with this now -- I'm also perfectly happy to merge this, and thank you :)

**Pull request merged**
